# Generated by Django 4.2 on 2026-04-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Mobile', 'Mobile'), ('Database', 'Database'), ('AI/ML', 'AI/ML'), ('Tools', 'Tools')], max_length=50)),
                ('level', models.IntegerField(default=5, help_text='Skill level from 1-10')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
    ]
