# Generated by Django 4.2 on 2026-04-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kur Malual', max_length=255)),
                ('title', models.CharField(default='Full-Stack Software Engineer', max_length=255)),
                ('tagline', models.TextField(default='Building Digital Systems That Work in the Real World')),
                ('description', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('email', models.EmailField(default='kurmalual@gmail.com', max_length=254)),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('location', models.CharField(default='Accra, Ghana', max_length=255)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
