# Generated by Django 4.2 on 2026-05-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Image for About Me section', null=True, upload_to='profile/about/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='journey_image',
            field=models.ImageField(blank=True, help_text='Image for My Journey section', null=True, upload_to='profile/journey/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Main profile image for hero section', null=True, upload_to='profile/'),
        ),
    ]
