# Generated by Django 4.2 on 2026-05-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='education/logos/'),
        ),
    ]
