import { Project } from '@/types/project';

export const projects: Project[] = [
  {
    title: 'Digital School Management System (DSMS)',
    slug: 'dsms',
    description: 'Enterprise school platform deployed in 3 secondary schools in Juba. Handles student registration, attendance, grading, fee management, teacher dashboards, and course registration. Works online and offline.',
    category: 'Systems',
    technologies: ['Django', 'PostgreSQL', 'JavaScript', 'REST APIs'],
    githubUrl: 'https://github.com',
    liveUrl: 'https://dsms.suddtech.com',
    featured: true,
    status: 'Live',
    impact: 'Used by 3 schools | 40% efficiency improvement',
  },
  {
    title: 'Resume Screening AI App',
    slug: 'resume-ai',
    description: 'Intelligent hiring tool using NLP and ML to match resumes to job descriptions and rank candidates by relevance.',
    category: 'AI',
    technologies: ['Python', 'Machine Learning', 'NLP', 'scikit-learn'],
    githubUrl: 'https://github.com',
    featured: false,
    status: 'Completed',
  },
  {
    title: 'SpeedyServe Food Delivery App',
    slug: 'speedyserve',
    description: 'Mobile app for ordering food from local restaurants with real-time delivery tracking and integrated payments.',
    category: 'Mobile',
    technologies: ['Flutter', 'Firebase', 'Dart'],
    githubUrl: 'https://github.com',
    featured: false,
    status: 'Completed',
  },
  {
    title: 'Agricultural Management Platform',
    slug: 'agri-platform',
    description: 'Connects farmers, equipment owners, transporters, and buyers on a single platform to reduce agricultural logistics disconnection.',
    category: 'Web',
    technologies: ['React', 'Django', 'CSS', 'MySQL'],
    githubUrl: 'https://github.com',
    featured: false,
    status: 'Completed',
  },
  {
    title: 'Ashesi Market E-Commerce',
    slug: 'ashesi-market',
    description: 'Campus marketplace enabling student vendors to list products, accept payments, and allow peer-to-peer borrowing.',
    category: 'Web',
    technologies: ['React', 'Node.js', 'Database Management'],
    githubUrl: 'https://github.com',
    featured: false,
    status: 'Completed',
  },
  {
    title: 'Eco-Adventure Tourism Platform',
    slug: 'eco-adventure',
    description: 'Travel booking platform for selecting destinations, reserving accommodations, and completing payments online.',
    category: 'Web',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    githubUrl: 'https://github.com',
    featured: false,
    status: 'Completed',
  },
  {
    title: 'SuddTech Company Website',
    slug: 'suddtech-website',
    description: 'Official website for SuddTech, a software company offering web, app, and digital product services.',
    category: 'Web',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    githubUrl: 'https://github.com',
    liveUrl: 'https://suddtech.com',
    featured: false,
    status: 'Live',
  },
];
