# Generated by Django 4.2 on 2026-05-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='achievements',
            field=models.TextField(blank=True, help_text='Comma-separated list of achievements'),
        ),
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, help_text='Image representing this role/position', null=True, upload_to='experience/'),
        ),
        migrations.AddField(
            model_name='experience',
            name='technologies',
            field=models.TextField(blank=True, help_text='Comma-separated list of technologies'),
        ),
    ]
