# Generated by Django 4.2 on 2026-04-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Systems', 'Systems'), ('Web', 'Web'), ('Mobile', 'Mobile'), ('AI', 'AI')], max_length=50)),
                ('technologies', models.TextField(default='[]', help_text='Comma-separated list of technologies')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Live', 'Live'), ('Completed', 'Completed'), ('In Progress', 'In Progress')], default='Completed', max_length=50)),
                ('impact', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
